### ISSUE TITLE
Improvement - services section 

### ISSUE THREAD

**Issue by devPalter** [Roxha-V/PTGA-Landing#27]
la visualizacion deberia ser de con dos elementos por fila

**Comment by devPalter** [comment]
se estima 3hs

**Comment by Roxha-V** [comment]
changes made and stashed, i preffer a review first or define some things about the carousel issue, before i can add the changes and create a pr, since it is posed differently by the client. The changes were made and stashed so that we could have them on hand and add these changes once the most important issue is resolved.
